Story/io 156/show category in planning list view
City-of-Helsinki/infraohjelmointi-ui pull request #34
Opened 2023-03-08 14:34 UTC by EngbergJonas

- Added category tag to planning table project header 
- Removed icons not to be used in MVP

2023-03-08 14:35 UTC, EngbergJonas commented
Should be merged after https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/26.

2023-03-16 08:49 UTC, kgunga requested changes

2023-03-16 08:49 UTC, kgunga commented on src/components/shared/CustomTag.tsx
wrap with memo because component is receiving properties

2023-03-16 10:09 UTC, EngbergJonas commented on src/components/shared/CustomTag.tsx
fixed

2023-03-16 10:26 UTC, kgunga approved these changes
👍

2023-03-16 10:30 UTC, merged