Story/io 151/modify cell years
City-of-Helsinki/infraohjelmointi-ui pull request #38
Opened 2023-03-16 10:20 UTC by EngbergJonas

2023-04-04 14:56 UTC, kgunga requested changes
Removing a value from cell with backspace and then clicking somewhere else removes the cell

2023-04-05 07:17 UTC, EngbergJonas commented on src/components/Planning/PlanningGroupsTable/ProjectCell.tsx
> +    if (i !== finances.length - 1) {
fixed

2023-04-05 07:17 UTC, EngbergJonas commented on src/components/Planning/PlanningGroupsTable/ProjectCell.tsx
> +    } else req.estPlanningEnd = removeYear(planEnd);
fixed

2023-04-13 05:09 UTC, kgunga requested changes

2023-04-13 05:09 UTC, kgunga commented on src/hooks/useIsInViewport.ts
>            setDimensions(bounding);
Make dimensions and isInViewPort states one state

2023-04-13 06:34 UTC, kgunga approved these changes

2023-04-13 06:42 UTC, merged