Story/io 205/planning list group structure
City-of-Helsinki/infraohjelmointi-ui pull request #41
Opened 2023-04-13 19:50 UTC by EngbergJonas

2023-04-24 07:07 UTC, kgunga requested changes

2023-04-24 07:07 UTC, kgunga commented on src/utils/interceptors.ts
> +  console.log('Error intercepted: ', error);
Remove this debugging log

2023-04-24 07:10 UTC, EngbergJonas commented on src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectRow.tsx
> +                <>
fixed

2023-04-24 07:11 UTC, EngbergJonas commented on src/utils/interceptors.ts
> +  console.log('Error intercepted: ', error);
fixed

2023-04-26 08:10 UTC, kgunga approved these changes
👍

2023-04-26 08:23 UTC, merged