Story/io 233/summary table monthly view
City-of-Helsinki/infraohjelmointi-ui pull request #48
Opened 2023-05-19 09:41 UTC by EngbergJonas

- Added monthly view to each year column in the PlanningViewSummary table
  - Added graph for each year in the monthly view that shows how much of each month is planning and construction
  - Added a line that shows the current date when the monthly view is expanded
- Changed ProjectCells to take planningStartYear and constructionEndYear into account when creating the timeline
- Changed ProjectBasicsForm to also patch the planningStartYear and constructionEndYear when estPlanningStart or estConstructionEnd is given or patched

2023-05-24 14:23 UTC, kgunga requested changes

2023-05-26 07:59 UTC, EngbergJonas commented on src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectYearSummary/MonthlyGraphCell.tsx
> +            className={`monthly-planning-bar-container ${planning.isStart ? 'justify-end' : ''}`}
Couldn't be done with the current element structure, added a comment...

2023-05-26 07:59 UTC, EngbergJonas commented on src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectYearSummary/MonthlyGraphCell.tsx
> +  const cellColor = useMemo(() => (index % 2 == 0 ? 'bg-bus-l' : 'bg-white'), [index]);
fixed

2023-05-26 07:59 UTC, EngbergJonas commented on src/components/Planning/PlanningTable/PlanningRow/PlanningCell.tsx
> +              {/* TODO: some stuff here */}
fixed

2023-05-26 07:59 UTC, EngbergJonas commented on src/components/Planning/PlanningTable/PlanningRow/PlanningCell.tsx
> +              {/* TODO: some stuff here */}
fixed

2023-05-26 08:00 UTC, EngbergJonas commented on src/components/Planning/PlanningSummaryTable/PlanningSummaryTableHeadCell.tsx
> +  const leftArrow = useMemo(
fixed

2023-05-26 11:36 UTC, kgunga approved these changes
👍

2023-05-26 11:45 UTC, merged