Story/io 334/construction program report
City-of-Helsinki/infraohjelmointi-ui pull request #84
Opened 2023-09-11 13:40 UTC by EngbergJonas

- Download construction program report in pdf format with react-pdf/renderer
- Download construction program report in csv format with react-csv

2023-09-14 12:07 UTC, kgunga requested changes

2023-09-14 12:07 UTC, kgunga commented on src/utils/calculations.ts
> +  if (value) {
if (!value) return '0,0';

const valueAsNumber = parseFloat(value);
    const millionValue = (valueAsNumber / 1000).toFixed(1);

    return millionValue.toString().replace('.', ',');

2023-09-15 06:59 UTC, EngbergJonas commented on src/components/Report/DownloadCsvButton.tsx
> +  const projects = await getProjectsWithParams({
fixed

2023-09-15 06:59 UTC, EngbergJonas commented on src/components/Report/DownloadCsvButton.tsx
> +  if (projects) {
fixed

2023-09-15 06:59 UTC, EngbergJonas commented on src/components/Report/DownloadCsvButton.tsx
> +  const downloadIcon = useMemo(() => <IconDownload />, []);
fixed

2023-09-15 06:59 UTC, EngbergJonas commented on src/components/Report/DownloadCsvButton.tsx
> +        // implemented later...
fixed

2023-09-15 06:59 UTC, EngbergJonas commented on src/components/Report/DownloadCsvButton.tsx
> +export default DownloadCsvButton;
fixed

2023-09-15 07:00 UTC, EngbergJonas commented on src/components/Report/DownloadPdfButton.tsx
> +export default DownloadPdfButton;
fixed

2023-09-15 07:00 UTC, EngbergJonas commented on src/utils/calculations.ts
> +  if (value) {
fixed

2023-09-15 09:12 UTC, kgunga approved these changes
👍

2023-09-15 09:14 UTC, merged